language: python
python:
  - 2.7
install:
  - pip install -r requirements/dev.txt --use-mirrors
env:
  - DJANGO_DEBUG=1 DATABASE_URL='postgres://localhost/pranger'
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database pranger;' -U postgres
  - ( cd pranger && ./manage.py migrate --noinput )
script:
  - ( cd pranger && python runtests.py )
